# -*- coding: utf-8 -*-
"""作業1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wly24CZmHsmZPT_gxdBbobi-JDU5_9Rd
"""

x=5
print(f"變數的x值:{x}")
print(f"變數的x的記憶體地址:{id(x)}")